# Generated by Django 2.1.3 on 2018-11-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingfragment',
            name='label',
            field=models.CharField(default='Sample', max_length=256),
            preserve_default=False,
        ),
    ]
